### ISSUE TITLE
Top down navigation

### ISSUE THREAD

**Issue by ryanhinkel** [wiota/facade#9]
I ran across a problem working on a category template. There was no way to pull the apex into the template dynamically.

Given a particular vertex, providing adjacent navigation is as simple as rendering the successors or predecessors as a list. But to provide a top down navigation I need a reference to the apex. With that reference, I could render the apex's successors as a standard navigation bar. I could even dereference one level down and have a dropdown navigation.

As much as I want to build sites that work on adjacent navigation schemes, I think it is probably important to have a top down option too.

**Comment by di** [comment]
{{ config["HOST"].apex }}

**Comment by ryanhinkel** [comment]
Great. I think it would be nice to have this reference as just `apex`.

**Comment by ryanhinkel** [comment]
`{ config["HOST"].apex }}` solves the immediate problem.
